services:
  - type: web
    name: mah-research-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: mah_research_db
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
